name: webpack-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: curl node-v18.12.1-win-x64.zip
        shell: cmd
        run: |
          curl https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip -L --output node-v18.12.1-win-x64.zip &&^
          7z.exe x node-v18.12.1-win-x64.zip
          
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
      
      - name: curl curl
        shell: cmd
        run: curl https://curl.se/windows/dl-8.6.0_4/curl-8.6.0_4-win64-mingw.zip -L --output curl-8.6.0_4-win64-mingw.zip && dir && 7z.exe x curl-8.6.0_4-win64-mingw.zip -o"curl-8.6.0_4-win64-mingw"
        
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            set PATH=^
            ${{ github.workspace }}\node-v18.12.1-win-x64;^
            ${{ github.workspace }}\PortableGit-2.38.1-64-bit\bin;^
            ${{ github.workspace }}\curl-8.6.0_4-win64-mingw\curl-8.6.0_4-win64-mingw\bin;
            npm i &&^
            npm run-script build
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "dist"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
